version: '2'
services:
  office4rent-app:
    image: office4rent
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://office4rent-mysql:3306/office4rent?useUnicode=true&characterEncoding=utf8&useSSL=false&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://office4rent-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://office4rent-elasticsearch:9200
    ports:
      - 8080:8080
  office4rent-mysql:
    extends:
      file: mysql.yml
      service: office4rent-mysql
  office4rent-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: office4rent-elasticsearch
